# Generated by Django 4.0.3 on 2022-03-13 02:33

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='petstagramuser',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
