# Generated by Django 4.0.3 on 2022-03-14 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_petphoto_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
